# Generated by Django 5.0.6 on 2024-07-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio_categoria_cor_marca_modelo_veiculo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veiculo",
            old_name="modelo",
            new_name="foto_veiculo",
        ),
    ]
