# Generated by Django 5.0.6 on 2024-07-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_veiculo_imagem_veiculo_modelo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="veiculos", to="core.modelo"
            ),
        ),
    ]
